CREATE DATABASE IF NOT EXISTS registro_usuarios
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE registro_usuarios;

CREATE TABLE IF NOT EXISTS usuarios (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
